language: node_js
node_js:
  - "9.10"
cache:
  directories:
    - "node_modules"
  yarn: true
install:
  - yarn install
branches:
  except:
    - gh-pages
script:
  - yarn deploy
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
branch: master
